=== matthewrcheng/NanoCards/entity_schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema",
    "$id": "https://example.com/entity_schema.json",
    "title": "JSON Schema for NanoCard Entities",
    "description": "Digital card battling game",
    "type": "object",
    "properties": {
        "name": {"type": "string"},
        "race": {
            "type": "string",
            "enum": ["Human", "Elf", "Dwarf", "Goblin", "Undead", "Skeleton", "Monster", "Giant", "Dragon"]
        },
        "class": {
            "type": "string",
            "enum": ["Warrior", "Mage", "Rogue", "Healer", "Ranger", "Tank"]
        },
        "element": {
            "type": "string",
            "enum": ["Fire", "Water", "Plant", "Earth", "Air", "Electric", "Light", "Dark"]
        },
        "health": {"type": "number"},
        "attack": {"type": "number"},
        "defense": {"type": "number"},
        "speed": {"type": "number"},
        "active_abilities": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "type": {
                        "type": "string",
                        "enum": ["attack", "heal", "modify", "status"]
                    },
                    "element": {
                        "type": "string",
                        "enum": ["Fire", "Water", "Plant", "Earth", "Air", "Electric", "Light", "Dark"]
                    },
                    "amount": {"type": "number"},
                    "effect": {"type": "array"},
                    "target": {
                        "type": "string",
                        "enum": ["Self", "Team", "Teammate", "Opponent", "Opponents"]
                    },
                    "energy": {"type": "number"}
                },
                "required": [ "name", "type", "element", "amount", "effect", "target", "energy" ]
            }
        },
        "passive_abilities": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "type": {
                        "type": "string",
                        "enum": ["attack"]
                    },
                    "element": {
                        "type": "string",
                        "enum": ["Fire", "Water", "Plant", "Earth", "Air", "Electric", "Light", "Dark"]
                    },
                    "amount": {"type": "number"}
                },
                "required": [ "name", "type", "element", "amount" ]
            }
        }
    },
    "required": [ "name", "race", "class", "element", "health", "attack", "defense", "speed", "active_abilities", "passive_abilities" ]
}

=== matthewrcheng/NanoCards/entities/heroes/goblino.entity.json
{
    "name": "Goblino",
    "race": "Goblin",
    "class": "Rogue",
    "element": "Air",
    "health": 12,
    "attack": 13,
    "defense": 11,
    "speed": 28,
    "active_abilities": [
        {
            "name": "Knife Gust",
            "type": "attack",
            "element": "Air",
            "amount": 3,
            "effect": [],
            "target": "Opponent",
            "energy": 1
        },
        {
            "name": "Surprise Attack",
            "type": "attack",
            "element": "Air",
            "amount": 6,
            "effect": [],
            "target": "Opponent",
            "energy": 3
        }
    ],
    "passive_abilities": []
}

=== matthewrcheng/NanoCards/entities/heroes/ignis.entity.json
{
    "name": "Ignis the Enchanter",
    "race": "Human",
    "class": "Mage",
    "element": "Fire",
    "health": 12,
    "attack": 24,
    "defense": 10,
    "speed": 20,
    "active_abilities": [
        {
            "name": "Fireball",
            "type": "attack",
            "element": "Fire",
            "amount": 3,
            "effect": [],
            "target": "Opponent",
            "energy": 1
        },
        {
            "name": "Wildfire",
            "type": "attack",
            "element": "Fire",
            "amount": 2,
            "effect": ["Burn,3,1"],
            "target": "Opponents",
            "energy": 4
        }
    ],
    "passive_abilities": []
}

=== matthewrcheng/NanoCards/entities/enemies/magma_skeletal_spellcaster.entity.json
{
    "name": "Magma Skeletal Warrior",
    "race": "Skeleton",
    "class": "Warrior",
    "element": "Fire",
    "health": 10,
    "attack": 10,
    "defense": 10,
    "speed": 14,
    "active_abilities": [
        {
            "name": "Fireball",
            "type": "attack",
            "element": "Fire",
            "amount": 3,
            "effect": [],
            "target": "Opponent",
            "energy": 1
        }
    ],
    "passive_abilities": []
}
