=== matthewrcheng/NanoCards/entity_schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema",
    "$id": "https://example.com/entity_schema.json",
    "title": "JSON Schema for NanoCard Entities",
    "description": "Digital card battling game",
    "type": "object",
    "properties": {
        "name": {"type": "string"},
        "race": {
            "type": "string",
            "enum": ["Human", "Elf", "Dwarf", "Goblin", "Undead", "Skeleton", "Monster", "Giant", "Dragon"]
        },
        "class": {
            "type": "string",
            "enum": ["Warrior", "Mage", "Rogue", "Healer", "Ranger", "Tank"]
        },
        "element": {
            "type": "string",
            "enum": ["Fire", "Water", "Plant", "Earth", "Air", "Electric", "Light", "Dark"]
        },
        "health": {"type": "number"},
        "attack": {"type": "number"},
        "defense": {"type": "number"},
        "speed": {"type": "number"},
        "active_abilities": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "type": {
                        "type": "string",
                        "enum": ["attack", "heal", "modify", "status"]
                    },
                    "element": {
                        "type": "string",
                        "enum": ["Fire", "Water", "Plant", "Earth", "Air", "Electric", "Light", "Dark"]
                    },
                    "amount": {"type": "number"},
                    "effect": {"type": "array"},
                    "target": {
                        "type": "string",
                        "enum": ["Self", "Team", "Teammate", "Opponent", "Opponents"]
                    },
                    "energy": {"type": "number"}
                },
                "required": [ "name", "type", "element", "amount", "effect", "target", "energy" ]
            }
        },
        "passive_abilities": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "type": {
                        "type": "string",
                        "enum": ["attack"]
                    },
                    "element": {
                        "type": "string",
                        "enum": ["Fire", "Water", "Plant", "Earth", "Air", "Electric", "Light", "Dark"]
                    },
                    "amount": {"type": "number"}
                },
                "required": [ "name", "type", "element", "amount" ]
            }
        }
    },
    "required": [ "name", "race", "class", "element", "health", "attack", "defense", "speed", "active_abilities", "passive_abilities" ]
}

=== matthewrcheng/NanoCards/entities/enemies/magma_skeletal_archer.entity.json
{
    "name": "Magma Skeletal Warrior",
    "race": "Skeleton",
    "class": "Warrior",
    "element": "Fire",
    "health": 10,
    "attack": 10,
    "defense": 10,
    "speed": 14,
    "active_abilities": [
        {
            "name": "Magma Bow",
            "type": "attack",
            "element": "Fire",
            "amount": 3,
            "effect": [],
            "target": "Opponent",
            "energy": 1
        }
    ],
    "passive_abilities": []
}

=== matthewrcheng/NanoCards/entities/enemies/dark_skeletal_spellcaster.entity.json
{
    "name": "Magma Skeletal Warrior",
    "race": "Skeleton",
    "class": "Warrior",
    "element": "Fire",
    "health": 10,
    "attack": 10,
    "defense": 10,
    "speed": 14,
    "active_abilities": [
        {
            "name": "Dark Energy",
            "type": "attack",
            "element": "Dark",
            "amount": 3,
            "effect": [],
            "target": "Opponent",
            "energy": 1
        }
    ],
    "passive_abilities": []
}

=== matthewrcheng/NanoCards/heroes/skulitan.entity.json
{
    "name": "Skulitan",
    "race": "Skeleton",
    "class": "Healer",
    "element": "Earth",
    "health": 8,
    "attack": 11,
    "defense": 9,
    "speed": 22,
    "active_abilities": [
        {
            "name": "Bone Club",
            "type": "attack",
            "element": "Earth",
            "amount": 3,
            "effect": [],
            "target": "Opponent",
            "energy": 1
        },
        {
            "name": "Necrotic Ritual",
            "type": "heal",
            "element": "Earth",
            "amount": 10,
            "effect": [],
            "target": "Team",
            "energy": 5
        },
        {
            "name": "Magic Stones",
            "type": "attack",
            "element": "Earth",
            "amount": 6,
            "effect": [],
            "target": "Opponent",
            "energy": 3
        }
    ],
    "passive_abilities": []
}

=== matthewrcheng/NanoCards/entities/enemies/magma_skeleton_king.entity.json
{
    "name": "Magma Skeletal Warrior",
    "race": "Skeleton",
    "class": "Warrior",
    "element": "Fire",
    "health": 100,
    "attack": 25,
    "defense": 25,
    "speed": 9,
    "active_abilities": [
        {
            "name": "Magma Fist",
            "type": "attack",
            "element": "Fire",
            "amount": 3,
            "effect": [],
            "target": "Opponent",
            "energy": 1
        },
        {
            "name": "Volcanic Eruption",
            "type": "attack",
            "element": "Fire",
            "amount": 3,
            "effect": [],
            "target": "Opponents",
            "energy": 5
        },
        {
            "name": "Infernal Roar",
            "type": "attack",
            "element": "Fire",
            "amount": 9,
            "effect": [],
            "target": "Opponent",
            "energy": 6
        },
        {
            "name": "Call of the Undead",
            "type": "attack",
            "element": "Dark",
            "amount": 7,
            "effect": [],
            "target": "Opponent",
            "energy": 3
        },
        {
            "name": "Fire Bone",
            "type": "attack",
            "element": "Fire",
            "amount": 12,
            "effect": [],
            "target": "Opponent",
            "energy": 8
        }
    ],
    "passive_abilities": []
}

=== matthewrcheng/NanoCards/entities/enemies/magma_skeletal_brute.entity.json
{
    "name": "Magma Skeletal Warrior",
    "race": "Skeleton",
    "class": "Warrior",
    "element": "Fire",
    "health": 30,
    "attack": 20,
    "defense": 20,
    "speed": 4,
    "active_abilities": [
        {
            "name": "Searing Charge",
            "type": "attack",
            "element": "Fire",
            "amount": 3,
            "effect": [],
            "target": "Opponent",
            "energy": 1
        },
        {
            "name": "Infernal Assault",
            "type": "attack",
            "element": "Fire",
            "amount": 3,
            "effect": [],
            "target": "Opponent",
            "energy": 1
        }
    ],
    "passive_abilities": []
}

=== matthewrcheng/NanoCards/entities/enemies/magma_goblin_trapper.entity.json
{
    "name": "Magma Goblin Trapper",
    "race": "Goblin",
    "class": "Rogue",
    "element": "Fire",
    "health": 10,
    "attack": 10,
    "defense": 10,
    "speed": 14,
    "active_abilities": [
        {
            "name": "Sneak Attack",
            "type": "attack",
            "element": "Fire",
            "amount": 3,
            "effect": [],
            "target": "Opponent",
            "energy": 1
        }
    ],
    "passive_abilities": []
}

=== matthewrcheng/NanoCards/entities/enemies/magma_skeletal_cleric.entity.json
{
    "name": "Magma Skeletal Cleric",
    "race": "Skeleton",
    "class": "Warrior",
    "element": "Fire",
    "health": 10,
    "attack": 10,
    "defense": 10,
    "speed": 14,
    "active_abilities": [
        {
            "name": "Lava Flow",
            "type": "attack",
            "element": "Fire",
            "amount": 3,
            "effect": [],
            "target": "Opponent",
            "energy": 1
        }
    ],
    "passive_abilities": []
}

=== matthewrcheng/NanoCards/entities/enemies/magma_goblin_bomber.entity.json
{
    "name": "Magma Goblin Bomber",
    "race": "Goblin",
    "class": "Rogue",
    "element": "Fire",
    "health": 10,
    "attack": 10,
    "defense": 10,
    "speed": 14,
    "active_abilities": [
        {
            "name": "Feint",
            "type": "attack",
            "element": "Fire",
            "amount": 3,
            "effect": [],
            "target": "Opponent",
            "energy": 1
        }
    ],
    "passive_abilities": []
}
